name: Waka Readme

on:
  push:
    branches: [main]
    paths:
    # run manually when modify this file
      - '.github/workflows/wakatime.yml'
  schedule:
    # Runs at 2am UTC
    - cron: '2 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # https://github.com/anmol098/waka-readme-stats?tab=readme-ov-file#flags-available
          SHOW_SHORT_INFO: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "True"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SYMBOL_VERSION: "1"
          DEBUG_LOGGING: "True"
